name: Terraform EC2 Provisioning
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provisioning AWS EC2 with Terraform
    runs-on: ubuntu-latest

    env:
      TF_CLOUD_ORGANIZATION: uday-devops-terraform
      TF_WORKSPACE: hashicorp-lab
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        run: terraform fmt -check
      
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve